# Generated by Django 5.0.3 on 2024-03-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='link',
            field=models.SlugField(max_length=250, verbose_name='Полная ссылка'),
        ),
    ]
